var allItems = {
    'emojis': {
        'title': 'Emojis 😃',
        'searchable' : true,
        'items': [
            { "s": "😀", "t": "face grin", "d": "grinning face" },
            { "s": "😁", "t": "eye face grin smile", "d": "grinning face with smiling eyes" },
            { "s": "😂", "t": "face joy laugh tear", "d": "face with tears of joy" },
            { "s": "🙃", "t": "face floor laugh rolling", "d": "rolling on the floor laughing" },
            { "s": "😃", "t": "face mouth open smile", "d": "smiling face with open mouth" },
            { "s": "😄", "t": "eye face mouth open smile", "d": "smiling face with open mouth & smiling eyes" },
            { "s": "😅", "t": "cold face open smile sweat", "d": "smiling face with open mouth & cold sweat" },
            { "s": "😆", "t": "face laugh mouth open satisfied smile", "d": "smiling face with open mouth & closed eyes" },
            { "s": "😉", "t": "face wink", "d": "winking face" },
            { "s": "😊", "t": "blush eye face smile", "d": "smiling face with smiling eyes" },
            { "s": "😋", "t": "delicious face savouring smile um yum", "d": "face savouring delicious food" },
            { "s": "😎", "t": "bright cool eye eyewear face glasses smile sun sunglasses", "d": "smiling face with sunglasses" },
            { "s": "😍", "t": "eye face love smile", "d": "smiling face with heart-eyes" },
            { "s": "😘", "t": "face kiss", "d": "face blowing a kiss" },
            { "s": "😗", "t": "face kiss", "d": "kissing face" },
            { "s": "😙", "t": "eye face kiss smile", "d": "kissing face with smiling eyes" },
            { "s": "😚", "t": "closed eye face kiss", "d": "kissing face with closed eyes" },
            { "s": "😛", "t": "face outlined relaxed smile", "d": "smiling face" },
            { "s": "🙂", "t": "face smile", "d": "slightly smiling face" },
            { "s": "🤗", "t": "face hug hugging", "d": "hugging face" },
            { "s": "🤔", "t": "face thinking", "d": "thinking face" },
            { "s": "😐", "t": "deadpan face neutral", "d": "neutral face" },
            { "s": "😑", "t": "expressionless face inexpressive unexpressive", "d": "expressionless face" },
            { "s": "😶", "t": "face mouth quiet silent", "d": "face without mouth" },
            { "s": "🙄", "t": "eyes face rolling", "d": "face with rolling eyes" },
            { "s": "😏", "t": "face smirk", "d": "smirking face" },
            { "s": "😣", "t": "face persevere", "d": "persevering face" },
            { "s": "😥", "t": "disappointed face relieved whew", "d": "disappointed but relieved face" },
            { "s": "😮", "t": "face mouth open sympathy", "d": "face with open mouth" },
            { "s": "🤐", "t": "face mouth zipper", "d": "zipper-mouth face" },
            { "s": "😯", "t": "face hushed stunned surprised", "d": "hushed face" },
            { "s": "😪", "t": "face sleep", "d": "sleepy face" },
            { "s": "😫", "t": "face tired", "d": "tired face" },
            { "s": "😴", "t": "face sleep zzz", "d": "sleeping face" },
            { "s": "😌", "t": "face relieved", "d": "relieved face" },
            { "s": "😛", "t": "face tongue", "d": "face with stuck-out tongue" },
            { "s": "😜", "t": "eye face joke tongue wink", "d": "face with stuck-out tongue & winking eye" },
            { "s": "😝", "t": "eye face horrible taste tongue", "d": "face with stuck-out tongue & closed eyes" },
            /*{ "s": "🤤", "t": "drooling face", "d": "drooling face" },*/
            { "s": "😒", "t": "face unamused unhappy", "d": "unamused face" },
            { "s": "😓", "t": "cold face sweat", "d": "face with cold sweat" },
            { "s": "😔", "t": "dejected face pensive", "d": "pensive face" },
            { "s": "😕", "t": "confused face", "d": "confused face" },
            { "s": "🙃", "t": "face upside-down", "d": "upside-down face" },
            { "s": "🤑", "t": "face money mouth", "d": "money-mouth face" },
            { "s": "😲", "t": "astonished face shocked totally", "d": "astonished face" },
            /*{ "s": "☹", "t": "face frown", "d": "frowning face" },*/
            { "s": "🙁", "t": "face frown", "d": "slightly frowning face" },
            { "s": "😖", "t": "confounded face", "d": "confounded face" },
            { "s": "😞", "t": "disappointed face", "d": "disappointed face" },
            { "s": "😟", "t": "face worried", "d": "worried face" },
            { "s": "😤", "t": "face triumph won", "d": "face with steam from nose" },
            { "s": "😢", "t": "cry face sad tear", "d": "crying face" },
            { "s": "😭", "t": "cry face sad sob tear", "d": "loudly crying face" },
            { "s": "😦", "t": "face frown mouth open", "d": "frowning face with open mouth" },
            { "s": "😧", "t": "anguished face", "d": "anguished face" },
            { "s": "😨", "t": "face fear fearful scared", "d": "fearful face" },
            { "s": "😩", "t": "face tired weary", "d": "weary face" },
            { "s": "😬", "t": "face grimace", "d": "grimacing face" },
            { "s": "😰", "t": "blue cold face mouth open rushed sweat", "d": "face with open mouth & cold sweat" },
            { "s": "😱", "t": "face fear fearful munch scared scream", "d": "face screaming in fear" },
            { "s": "😳", "t": "dazed face flushed", "d": "flushed face" },
            { "s": "😵", "t": "dizzy face", "d": "dizzy face" },
            { "s": "😡", "t": "angry face mad pouting rage red", "d": "pouting face" },
            { "s": "😠", "t": "angry face mad", "d": "angry face" },
            { "s": "😷", "t": "cold doctor face mask medicine sick", "d": "face with medical mask" },
            { "s": "🤒", "t": "face ill sick thermometer", "d": "face with thermometer" },
            { "s": "🤕", "t": "bandage face hurt injury", "d": "face with head-bandage" },
            /*{ "s": "🤢", "t": "face nauseated vomit", "d": "nauseated face" },*/
            /*{ "s": "🤧", "t": "face gesundheit sneeze", "d": "sneezing face" },*/
            { "s": "😇", "t": "angel face fairy tale fantasy halo innocent smile", "d": "smiling face with halo" },
            /*
            { "s": "🤠", "t": "cowboy cowgirl face hat", "d": "cowboy hat face" },
            { "s": "🤡", "t": "clown face", "d": "clown face" },
            { "s": "🤥", "t": "face lie pinocchio", "d": "lying face" },
            */
            { "s": "🤓", "t": "face geek nerd", "d": "nerd face" },
            { "s": "😈", "t": "face fairy tale fantasy horns smile", "d": "smiling face with horns" },
            { "s": "👿", "t": "demon devil face fairy tale fantasy imp", "d": "angry face with horns" },
            { "s": "👹", "t": "creature face fairy tale fantasy monster", "d": "ogre" },
            { "s": "👺", "t": "creature face fairy tale fantasy monster", "d": "goblin" },
            { "s": "💀", "t": "death face fairy tale monster", "d": "skull" },
            { "s": "☠", "t": "crossbones death face monster skull", "d": "skull and crossbones" },
            { "s": "👻", "t": "creature face fairy tale fantasy monster", "d": "ghost" },
            { "s": "👽", "t": "creature extraterrestrial face fairy tale fantasy monster ufo", "d": "alien" },
            { "s": "👾", "t": "alien creature extraterrestrial face fairy tale fantasy monster ufo", "d": "alien monster" },
            { "s": "🤖", "t": "face monster robot", "d": "robot face" },
            { "s": "💩", "t": "comic dung face monster poo poop", "d": "pile of poo" },
            { "s": "😺", "t": "cat face mouth open smile", "d": "smiling cat face with open mouth" },
            { "s": "😸", "t": "cat eye face grin smile", "d": "grinning cat face with smiling eyes" },
            { "s": "😹", "t": "cat face joy tear", "d": "cat face with tears of joy" },
            { "s": "😻", "t": "cat eye face love smile", "d": "smiling cat face with heart-eyes" },
            { "s": "😼", "t": "cat face ironic smile wry", "d": "cat face with wry smile" },
            { "s": "😽", "t": "cat eye face kiss", "d": "kissing cat face with closed eyes" },
            { "s": "🙀", "t": "cat face oh surprised weary", "d": "weary cat face" },
            { "s": "😿", "t": "cat cry face sad tear", "d": "crying cat face" },
            { "s": "😾", "t": "cat face pouting", "d": "pouting cat face" },
            { "s": "🙈", "t": "evil face forbidden gesture monkey no not prohibited see", "d": "see-no-evil monkey" },
            { "s": "🙉", "t": "evil face forbidden gesture hear monkey no not prohibited", "d": "hear-no-evil monkey" },
            { "s": "🙊", "t": "evil face forbidden gesture monkey no not prohibited speak", "d": "speak-no-evil monkey" },
            /*
            { "s": "🏻", "t": "skin tone type 1–2", "d": "light skin tone" },
            { "s": "🏼", "t": "skin tone type 3", "d": "medium-light skin tone" },
            { "s": "🏽", "t": "skin tone type 4", "d": "medium skin tone" },
            { "s": "🏾", "t": "skin tone type 5", "d": "medium-dark skin tone" },
            { "s": "🏿", "t": "skin tone type 6", "d": "dark skin tone" },
            */
            { "s": "👶", "t": "baby young", "d": "baby" },
            { "s": "👦", "t": "boy young", "d": "boy" },
            { "s": "👧", "t": "Virgo young zodiac", "d": "girl" },
            { "s": "👨", "t": "man", "d": "man" },
            { "s": "👩", "t": "woman", "d": "woman" },
            { "s": "👴", "t": "man old", "d": "old man" },
            { "s": "👵", "t": "old woman", "d": "old woman" },
            { "s": "👮", "t": "cop officer police", "d": "police officer" },
            { "s": "🕵", "t": "detective sleuth spy", "d": "detective" },
            { "s": "💂", "t": "guard", "d": "guard" },
            { "s": "👷", "t": "construction hat worker", "d": "construction worker" },
            { "s": "🤴", "t": "prince", "d": "prince" },
            { "s": "👸", "t": "fairy tale fantasy", "d": "princess" },
            { "s": "👳", "t": "turban", "d": "person wearing turban" },
            { "s": "👲", "t": "gua pi mao hat man", "d": "man with Chinese cap" },
            { "s": "👱", "t": "blond", "d": "blond-haired person" },
            { "s": "🤵", "t": "groom man tuxedo", "d": "man in tuxedo" },
            { "s": "👰", "t": "bride veil wedding", "d": "bride with veil" },
            { "s": "🤰", "t": "pregnant woman", "d": "pregnant woman" },
            { "s": "👼", "t": "angel baby face fairy tale fantasy", "d": "baby angel" },
            { "s": "🎅", "t": "celebration Christmas claus father santa", "d": "Santa Claus" },
            { "s": "🤶", "t": "celebration Christmas claus mother Mrs.", "d": "Mrs. Claus" },
            { "s": "🙍", "t": "frown gesture", "d": "person frowning" },
            { "s": "🙎", "t": "gesture pouting", "d": "person pouting" },
            { "s": "🙅", "t": "forbidden gesture hand no not prohibited", "d": "person gesturing NO" },
            { "s": "🙆", "t": "gesture hand OK", "d": "person gesturing OK" },
            { "s": "💁", "t": "hand help information sassy tipping", "d": "person tipping hand" },
            { "s": "🙋", "t": "gesture hand happy raised", "d": "person raising hand" },
            { "s": "🙇", "t": "apology bow gesture sorry", "d": "person bowing" },
            { "s": "🤦", "t": "disbelief exasperation face palm", "d": "person facepalming" },
            { "s": "🤷", "t": "doubt ignorance indifference shrug", "d": "person shrugging" },
            { "s": "💆", "t": "face massage salon", "d": "person getting massage" },
            { "s": "💇", "t": "barber beauty haircut parlor", "d": "person getting haircut" },
            { "s": "🚶", "t": "hike walk walking", "d": "person walking" },
            { "s": "🏃", "t": "marathon running", "d": "person running" },
            { "s": "💃", "t": "dancing woman", "d": "woman dancing" },
            { "s": "🕺", "t": "dance man", "d": "man dancing" },
            { "s": "👯", "t": "bunny ear dancer partying", "d": "people with bunny ears partying" },
            { "s": "🛀", "t": "bath bathtub", "d": "person taking bath" },
            { "s": "🛌", "t": "hotel sleep", "d": "person in bed" },
            { "s": "🕴", "t": "business man suit", "d": "man in business suit levitating" },
            { "s": "🗣", "t": "face head silhouette speak speaking", "d": "speaking head" },
            { "s": "👤", "t": "bust silhouette", "d": "bust in silhouette" },
            { "s": "👥", "t": "bust silhouette", "d": "busts in silhouette" },
            { "s": "🤺", "t": "fencer fencing sword", "d": "person fencing" },
            { "s": "🏇", "t": "horse jockey racehorse racing", "d": "horse racing" },
            { "s": "⛷", "t": "ski snow", "d": "skier" },
            { "s": "🏂", "t": "ski snow snowboard", "d": "snowboarder" },
            { "s": "🏌", "t": "ball golf", "d": "person golfing" },
            { "s": "🏄", "t": "surfing", "d": "person surfing" },
            { "s": "🚣", "t": "boat rowboat", "d": "person rowing boat" },
            { "s": "🏊", "t": "swim", "d": "person swimming" },
            { "s": "⛹", "t": "ball", "d": "person bouncing ball" },
            { "s": "🏋", "t": "lifter weight", "d": "person lifting weights" },
            { "s": "🚴", "t": "bicycle biking cyclist", "d": "person biking" },
            { "s": "🚵", "t": "bicycle bicyclist bike cyclist mountain", "d": "person mountain biking" },
            { "s": "🏎", "t": "car racing", "d": "racing car" },
            { "s": "🏍", "t": "racing", "d": "motorcycle" },
            { "s": "🤸", "t": "cartwheel gymnastics", "d": "person cartwheeling" },
            { "s": "🤼", "t": "wrestle wrestler", "d": "people wrestling" },
            { "s": "🤽", "t": "polo water", "d": "person playing water polo" },
            { "s": "🤾", "t": "ball handball", "d": "person playing handball" },
            { "s": "🤹", "t": "balance juggle multitask skill", "d": "person juggling" },
            { "s": "👫", "t": "couple hand hold man woman", "d": "man and woman holding hands" },
            { "s": "👬", "t": "couple Gemini hand hold man twins zodiac", "d": "two men holding hands" },
            { "s": "👭", "t": "couple hand hold woman", "d": "two women holding hands" },
            { "s": "💏", "t": "couple", "d": "kiss" },
            { "s": "💑", "t": "couple love", "d": "couple with heart" },
            { "s": "👪", "t": "family", "d": "family" },
            { "s": "🤳", "t": "camera phone selfie", "d": "selfie" },
            { "s": "💪", "t": "biceps comic flex muscle", "d": "flexed biceps" },
            { "s": "👈", "t": "backhand finger hand index point", "d": "backhand index pointing left" },
            { "s": "👉", "t": "backhand finger hand index point", "d": "backhand index pointing right" },
            { "s": "☝", "t": "finger hand index point up", "d": "index pointing up" },
            { "s": "👆", "t": "backhand finger hand index point up", "d": "backhand index pointing up" },
            { "s": "🖕", "t": "finger hand", "d": "middle finger" },
            { "s": "👇", "t": "backhand down finger hand index point", "d": "backhand index pointing down" },
            { "s": "✌", "t": "hand v victory", "d": "victory hand" },
            { "s": "🤞", "t": "cross finger hand luck", "d": "crossed fingers" },
            { "s": "🖖", "t": "finger hand spock vulcan", "d": "vulcan salute" },
            { "s": "🤘", "t": "finger hand horns rock-on", "d": "sign of the horns" },
            { "s": "🤙", "t": "call hand", "d": "call me hand" },
            { "s": "🖐", "t": "finger hand splayed", "d": "raised hand with fingers splayed" },
            { "s": "✋", "t": "hand", "d": "raised hand" },
            { "s": "👌", "t": "hand OK", "d": "OK hand" },
            { "s": "👎", "t": "-1 down hand thumb", "d": "thumbs down" },
            { "s": "✊", "t": "clenched fist hand punch", "d": "raised fist" },
            { "s": "👊", "t": "clenched fist hand punch", "d": "oncoming fist" },
            { "s": "🤛", "t": "fist leftwards", "d": "left-facing fist" },
            { "s": "🤜", "t": "fist rightwards", "d": "right-facing fist" },
            { "s": "🤚", "t": "backhand raised", "d": "raised back of hand" },
            { "s": "👋", "t": "hand wave waving", "d": "waving hand" },
            { "s": "✍", "t": "hand write", "d": "writing hand" },
            { "s": "👏", "t": "clap hand", "d": "clapping hands" },
            { "s": "👐", "t": "hand open", "d": "open hands" },
            { "s": "🙌", "t": "celebration gesture hand hooray raised", "d": "raising hands" },
            { "s": "🙏", "t": "ask bow folded gesture hand please pray thanks", "d": "folded hands" },
            { "s": "🤝", "t": "agreement hand handshake meeting shake", "d": "handshake" },
            { "s": "💅", "t": "care cosmetics manicure nail polish", "d": "nail polish" },
            { "s": "👂", "t": "body", "d": "ear" },
            { "s": "👃", "t": "body", "d": "nose" },
            { "s": "👣", "t": "clothing footprint print", "d": "footprints" },
            { "s": "👀", "t": "eye face", "d": "eyes" },
            { "s": "👁", "t": "body", "d": "eye" },
            { "s": "👅", "t": "body", "d": "tongue" },
            { "s": "👄", "t": "lips", "d": "mouth" },
            { "s": "💋", "t": "kiss lips", "d": "kiss mark" },
            { "s": "💘", "t": "arrow cupid", "d": "heart with arrow" },
            { "s": "❤", "t": "heart", "d": "red heart" },
            { "s": "💓", "t": "beating heartbeat pulsating", "d": "beating heart" },
            { "s": "💔", "t": "break broken", "d": "broken heart" },
            { "s": "💕", "t": "love", "d": "two hearts" },
            { "s": "💖", "t": "excited sparkle", "d": "sparkling heart" },
            { "s": "💗", "t": "excited growing nervous pulse", "d": "growing heart" },
            { "s": "💙", "t": "blue", "d": "blue heart" },
            { "s": "💚", "t": "green", "d": "green heart" },
            { "s": "💛", "t": "yellow", "d": "yellow heart" },
            { "s": "💜", "t": "purple", "d": "purple heart" },
            { "s": "🖤", "t": "black evil wicked", "d": "black heart" },
            { "s": "💝", "t": "ribbon valentine", "d": "heart with ribbon" },
            { "s": "💞", "t": "revolving", "d": "revolving hearts" },
            { "s": "💟", "t": "heart", "d": "heart decoration" },
            { "s": "❣", "t": "exclamation mark punctuation", "d": "heavy heart exclamation" },
            { "s": "💌", "t": "heart letter love mail", "d": "love letter" },
            { "s": "💤", "t": "comic sleep", "d": "zzz" },
            { "s": "💢", "t": "angry comic mad", "d": "anger symbol" },
            { "s": "💣", "t": "comic", "d": "bomb" },
            { "s": "💥", "t": "boom comic", "d": "collision" },
            { "s": "💦", "t": "comic splashing sweat", "d": "sweat droplets" },
            { "s": "💨", "t": "comic dash running", "d": "dashing away" },
            { "s": "💫", "t": "comic star", "d": "dizzy" },
            { "s": "💬", "t": "balloon bubble comic dialog speech", "d": "speech balloon" },
            { "s": "🗨", "t": "dialog speech", "d": "left speech bubble" },
            { "s": "🗯", "t": "angry balloon bubble mad", "d": "right anger bubble" },
            { "s": "💭", "t": "balloon bubble comic thought", "d": "thought balloon" },
            { "s": "🕳", "t": "hole", "d": "hole" },
            { "s": "👓", "t": "clothing eye eyeglasses eyewear", "d": "glasses" },
            { "s": "🕶", "t": "dark eye eyewear glasses", "d": "sunglasses" },
            { "s": "👔", "t": "clothing", "d": "necktie" },
            { "s": "👕", "t": "clothing shirt tshirt", "d": "t-shirt" },
            { "s": "👖", "t": "clothing pants trousers", "d": "jeans" },
            { "s": "👗", "t": "clothing", "d": "dress" },
            { "s": "👘", "t": "clothing", "d": "kimono" },
            { "s": "👙", "t": "clothing swim", "d": "bikini" },
            { "s": "👚", "t": "clothing woman", "d": "woman’s clothes" },
            { "s": "👛", "t": "clothing coin", "d": "purse" },
            { "s": "👜", "t": "bag clothing purse", "d": "handbag" },
            { "s": "👝", "t": "bag clothing pouch", "d": "clutch bag" },
            { "s": "🛍", "t": "bag hotel shopping", "d": "shopping bags" },
            { "s": "🎒", "t": "bag satchel school", "d": "school backpack" },
            { "s": "👞", "t": "clothing man shoe", "d": "man’s shoe" },
            { "s": "👟", "t": "athletic clothing shoe sneaker", "d": "running shoe" },
            { "s": "👠", "t": "clothing heel shoe woman", "d": "high-heeled shoe" },
            { "s": "👡", "t": "clothing sandal shoe woman", "d": "woman’s sandal" },
            { "s": "👢", "t": "boot clothing shoe woman", "d": "woman’s boot" },
            { "s": "👑", "t": "clothing king queen", "d": "crown" },
            { "s": "👒", "t": "clothing hat woman", "d": "woman’s hat" },
            { "s": "🎩", "t": "clothing hat top tophat", "d": "top hat" },
            { "s": "🎓", "t": "cap celebration clothing graduation hat", "d": "graduation cap" },
            { "s": "⛑", "t": "aid cross face hat helmet", "d": "rescue worker’s helmet" },
            { "s": "📿", "t": "beads clothing necklace prayer religion", "d": "prayer beads" },
            { "s": "💄", "t": "cosmetics makeup", "d": "lipstick" },
            { "s": "💍", "t": "diamond", "d": "ring" },
            { "s": "💎", "t": "diamond gem jewel", "d": "gem stone" },
            { "s": "🐵", "t": "face monkey", "d": "monkey face" },
            { "s": "🐒", "t": "monkey", "d": "monkey" },
            { "s": "🦍", "t": "gorilla", "d": "gorilla" },
            { "s": "🐶", "t": "dog face pet", "d": "dog face" },
            { "s": "🐕", "t": "pet", "d": "dog" },
            { "s": "🐩", "t": "dog", "d": "poodle" },
            { "s": "🐺", "t": "face wolf", "d": "wolf face" },
            { "s": "🦊", "t": "face fox", "d": "fox face" },
            { "s": "🐱", "t": "cat face pet", "d": "cat face" },
            { "s": "🐈", "t": "pet", "d": "cat" },
            { "s": "🦁", "t": "face Leo lion zodiac", "d": "lion face" },
            { "s": "🐯", "t": "face tiger", "d": "tiger face" },
            { "s": "🐅", "t": "tiger", "d": "tiger" },
            { "s": "🐆", "t": "leopard", "d": "leopard" },
            { "s": "🐴", "t": "face horse", "d": "horse face" },
            { "s": "🐎", "t": "equestrian racehorse racing", "d": "horse" },
            { "s": "🦄", "t": "face unicorn", "d": "unicorn face" },
            { "s": "🦌", "t": "deer", "d": "deer" },
            { "s": "🐮", "t": "cow face", "d": "cow face" },
            { "s": "🐂", "t": "bull Taurus zodiac", "d": "ox" },
            { "s": "🐃", "t": "buffalo water", "d": "water buffalo" },
            { "s": "🐄", "t": "cow", "d": "cow" },
            { "s": "🐷", "t": "face pig", "d": "pig face" },
            { "s": "🐖", "t": "sow", "d": "pig" },
            { "s": "🐗", "t": "pig", "d": "boar" },
            { "s": "🐽", "t": "face nose pig", "d": "pig nose" },
            { "s": "🐏", "t": "Aries male sheep zodiac", "d": "ram" },
            { "s": "🐑", "t": "female sheep", "d": "ewe" },
            { "s": "🐐", "t": "Capricorn zodiac", "d": "goat" },
            { "s": "🐪", "t": "dromedary hump", "d": "camel" },
            { "s": "🐫", "t": "bactrian camel hump", "d": "two-hump camel" },
            { "s": "🐘", "t": "elephant", "d": "elephant" },
            { "s": "🦏", "t": "rhinoceros", "d": "rhinoceros" },
            { "s": "🐭", "t": "face mouse", "d": "mouse face" },
            { "s": "🐁", "t": "mouse", "d": "mouse" },
            { "s": "🐀", "t": "rat", "d": "rat" },
            { "s": "🐹", "t": "face hamster pet", "d": "hamster face" },
            { "s": "🐰", "t": "bunny face pet rabbit", "d": "rabbit face" },
            { "s": "🐇", "t": "bunny pet", "d": "rabbit" },
            { "s": "🐿", "t": "chipmunk", "d": "chipmunk" },
            { "s": "🦇", "t": "bat vampire", "d": "bat" },
            { "s": "🐻", "t": "bear face", "d": "bear face" },
            { "s": "🐨", "t": "bear", "d": "koala" },
            { "s": "🐼", "t": "face panda", "d": "panda face" },
            { "s": "🐾", "t": "feet paw print", "d": "paw prints" },
            { "s": "🦃", "t": "bird turkey", "d": "turkey" },
            { "s": "🐔", "t": "bird chicken", "d": "chicken" },
            { "s": "🐓", "t": "bird rooster", "d": "rooster" },
            { "s": "🐣", "t": "baby bird chick hatching", "d": "hatching chick" },
            { "s": "🐤", "t": "baby bird chick", "d": "baby chick" },
            { "s": "🐥", "t": "baby bird chick", "d": "front-facing baby chick" },
            { "s": "🐦", "t": "bird", "d": "bird" },
            { "s": "🐧", "t": "bird penguin", "d": "penguin" },
            { "s": "🕊", "t": "bird fly peace", "d": "dove" },
            { "s": "🦅", "t": "bird eagle", "d": "eagle" },
            { "s": "🦆", "t": "bird duck", "d": "duck" },
            { "s": "🦉", "t": "bird owl wise", "d": "owl" },
            { "s": "🐸", "t": "face frog", "d": "frog face" },
            { "s": "🐊", "t": "crocodile", "d": "crocodile" },
            { "s": "🐢", "t": "terrapin tortoise turtle", "d": "turtle" },
            { "s": "🦎", "t": "lizard reptile", "d": "lizard" },
            { "s": "🐍", "t": "bearer Ophiuchus serpent zodiac", "d": "snake" },
            { "s": "🐲", "t": "dragon face fairy tale", "d": "dragon face" },
            { "s": "🐉", "t": "fairy tale", "d": "dragon" },
            { "s": "🐳", "t": "face spouting whale", "d": "spouting whale" },
            { "s": "🐋", "t": "whale", "d": "whale" },
            { "s": "🐬", "t": "flipper", "d": "dolphin" },
            { "s": "🐟", "t": "Pisces zodiac", "d": "fish" },
            { "s": "🐠", "t": "fish tropical", "d": "tropical fish" },
            { "s": "🐡", "t": "fish", "d": "blowfish" },
            { "s": "🦈", "t": "fish shark", "d": "shark" },
            { "s": "🐙", "t": "octopus", "d": "octopus" },
            { "s": "🐚", "t": "shell spiral", "d": "spiral shell" },
            { "s": "🦀", "t": "Cancer zodiac", "d": "crab" },
            { "s": "🦐", "t": "food shellfish shrimp small", "d": "shrimp" },
            { "s": "🦑", "t": "food molusc squid", "d": "squid" },
            { "s": "🐌", "t": "snail", "d": "snail" },
            { "s": "🦋", "t": "butterfly insect pretty", "d": "butterfly" },
            { "s": "🐛", "t": "insect", "d": "bug" },
            { "s": "🐜", "t": "insect", "d": "ant" },
            { "s": "🐝", "t": "bee insect", "d": "honeybee" },
            { "s": "🐞", "t": "beetle insect ladybird ladybug", "d": "lady beetle" },
            { "s": "🕷", "t": "insect", "d": "spider" },
            { "s": "🕸", "t": "spider web", "d": "spider web" },
            { "s": "🦂", "t": "scorpio Scorpius zodiac", "d": "scorpion" },
            { "s": "💐", "t": "flower", "d": "bouquet" },
            { "s": "🌸", "t": "blossom cherry flower", "d": "cherry blossom" },
            { "s": "💮", "t": "flower", "d": "white flower" },
            { "s": "🏵", "t": "plant", "d": "rosette" },
            { "s": "🌹", "t": "flower", "d": "rose" },
            { "s": "🥀", "t": "flower wilted", "d": "wilted flower" },
            { "s": "🌺", "t": "flower", "d": "hibiscus" },
            { "s": "🌻", "t": "flower sun", "d": "sunflower" },
            { "s": "🌼", "t": "flower", "d": "blossom" },
            { "s": "🌷", "t": "flower", "d": "tulip" },
            { "s": "🌱", "t": "young", "d": "seedling" },
            { "s": "🌲", "t": "tree", "d": "evergreen tree" },
            { "s": "🌳", "t": "deciduous shedding tree", "d": "deciduous tree" },
            { "s": "🌴", "t": "palm tree", "d": "palm tree" },
            { "s": "🌵", "t": "plant", "d": "cactus" },
            { "s": "🌾", "t": "ear grain rice", "d": "sheaf of rice" },
            { "s": "🌿", "t": "leaf", "d": "herb" },
            { "s": "☘", "t": "plant", "d": "shamrock" },
            { "s": "🍀", "t": "4 clover four leaf", "d": "four leaf clover" },
            { "s": "🍁", "t": "falling leaf maple", "d": "maple leaf" },
            { "s": "🍂", "t": "falling leaf", "d": "fallen leaf" },
            { "s": "🍃", "t": "blow flutter leaf wind", "d": "leaf fluttering in wind" },
            { "s": "🍇", "t": "fruit grape", "d": "grapes" },
            { "s": "🍈", "t": "fruit", "d": "melon" },
            { "s": "🍉", "t": "fruit", "d": "watermelon" },
            { "s": "🍊", "t": "fruit orange", "d": "tangerine" },
            { "s": "🍋", "t": "citrus fruit", "d": "lemon" },
            { "s": "🍌", "t": "fruit", "d": "banana" },
            { "s": "🍍", "t": "fruit", "d": "pineapple" },
            { "s": "🍎", "t": "apple fruit red", "d": "red apple" },
            { "s": "🍏", "t": "apple fruit green", "d": "green apple" },
            { "s": "🍐", "t": "fruit", "d": "pear" },
            { "s": "🍑", "t": "fruit", "d": "peach" },
            { "s": "🍒", "t": "cherry fruit", "d": "cherries" },
            { "s": "🍓", "t": "berry fruit", "d": "strawberry" },
            { "s": "🥝", "t": "food fruit kiwi", "d": "kiwi fruit" },
            { "s": "🍅", "t": "fruit vegetable", "d": "tomato" },
            { "s": "🥑", "t": "avocado food fruit", "d": "avocado" },
            { "s": "🍆", "t": "aubergine vegetable", "d": "eggplant" },
            { "s": "🥔", "t": "food potato vegetable", "d": "potato" },
            { "s": "🥕", "t": "carrot food vegetable", "d": "carrot" },
            { "s": "🌽", "t": "corn ear maize maze", "d": "ear of corn" },
            { "s": "🌶", "t": "hot pepper", "d": "hot pepper" },
            { "s": "🥒", "t": "cucumber food pickle vegetable", "d": "cucumber" },
            { "s": "🍄", "t": "toadstool", "d": "mushroom" },
            { "s": "🥜", "t": "food nut peanut vegetable", "d": "peanuts" },
            { "s": "🌰", "t": "plant", "d": "chestnut" },
            { "s": "🍞", "t": "loaf", "d": "bread" },
            { "s": "🥐", "t": "bread crescent roll croissant food french", "d": "croissant" },
            { "s": "🥖", "t": "baguette bread food french", "d": "baguette bread" },
            { "s": "🥞", "t": "crêpe food hotcake pancake", "d": "pancakes" },
            { "s": "🧀", "t": "cheese", "d": "cheese wedge" },
            { "s": "🍖", "t": "bone meat", "d": "meat on bone" },
            { "s": "🍗", "t": "bone chicken leg poultry", "d": "poultry leg" },
            { "s": "🥓", "t": "bacon food meat", "d": "bacon" },
            { "s": "🍔", "t": "burger", "d": "hamburger" },
            { "s": "🍟", "t": "french fries", "d": "french fries" },
            { "s": "🍕", "t": "cheese slice", "d": "pizza" },
            { "s": "🌭", "t": "frankfurter hotdog sausage", "d": "hot dog" },
            { "s": "🌮", "t": "mexican", "d": "taco" },
            { "s": "🌯", "t": "mexican wrap", "d": "burrito" },
            { "s": "🥙", "t": "falafel flatbread food gyro kebab stuffed", "d": "stuffed flatbread" },
            { "s": "🥚", "t": "egg food", "d": "egg" },
            { "s": "🍳", "t": "egg frying pan", "d": "cooking" },
            { "s": "🥘", "t": "casserole food paella pan shallow", "d": "shallow pan of food" },
            { "s": "🍲", "t": "pot stew", "d": "pot of food" },
            { "s": "🥗", "t": "food green salad", "d": "green salad" },
            { "s": "🍿", "t": "popcorn", "d": "popcorn" },
            { "s": "🍱", "t": "bento box", "d": "bento box" },
            { "s": "🍘", "t": "cracker rice", "d": "rice cracker" },
            { "s": "🍙", "t": "ball Japanese rice", "d": "rice ball" },
            { "s": "🍚", "t": "cooked rice", "d": "cooked rice" },
            { "s": "🍛", "t": "curry rice", "d": "curry rice" },
            { "s": "🍜", "t": "bowl noodle ramen steaming", "d": "steaming bowl" },
            { "s": "🍝", "t": "pasta", "d": "spaghetti" },
            { "s": "🍠", "t": "potato roasted sweet", "d": "roasted sweet potato" },
            { "s": "🍢", "t": "kebab seafood skewer stick", "d": "oden" },
            { "s": "🍣", "t": "sushi", "d": "sushi" },
            { "s": "🍤", "t": "fried prawn shrimp tempura", "d": "fried shrimp" },
            { "s": "🍥", "t": "cake fish pastry swirl", "d": "fish cake with swirl" },
            { "s": "🍡", "t": "dessert Japanese skewer stick sweet", "d": "dango" },
            { "s": "🍦", "t": "cream dessert ice icecream soft sweet", "d": "soft ice cream" },
            { "s": "🍧", "t": "dessert ice shaved sweet", "d": "shaved ice" },
            { "s": "🍨", "t": "cream dessert ice sweet", "d": "ice cream" },
            { "s": "🍩", "t": "dessert donut sweet", "d": "doughnut" },
            { "s": "🍪", "t": "dessert sweet", "d": "cookie" },
            { "s": "🎂", "t": "birthday cake celebration dessert pastry sweet", "d": "birthday cake" },
            { "s": "🍰", "t": "cake dessert pastry slice sweet", "d": "shortcake" },
            { "s": "🍫", "t": "bar chocolate dessert sweet", "d": "chocolate bar" },
            { "s": "🍬", "t": "dessert sweet", "d": "candy" },
            { "s": "🍭", "t": "candy dessert sweet", "d": "lollipop" },
            { "s": "🍮", "t": "dessert pudding sweet", "d": "custard" },
            { "s": "🍯", "t": "honey honeypot pot sweet", "d": "honey pot" },
            { "s": "🍼", "t": "baby bottle drink milk", "d": "baby bottle" },
            { "s": "🥛", "t": "drink glass milk", "d": "glass of milk" },
            { "s": "☕", "t": "beverage coffee drink hot steaming tea", "d": "hot beverage" },
            { "s": "🍵", "t": "beverage cup drink tea teacup", "d": "teacup without handle" },
            { "s": "🍶", "t": "bar beverage bottle cup drink", "d": "sake" },
            { "s": "🍾", "t": "bar bottle cork drink popping", "d": "bottle with popping cork" },
            { "s": "🍷", "t": "bar beverage drink glass wine", "d": "wine glass" },
            { "s": "🍸", "t": "bar cocktail drink glass", "d": "cocktail glass" },
            { "s": "🍹", "t": "bar drink tropical", "d": "tropical drink" },
            { "s": "🍺", "t": "bar beer drink mug", "d": "beer mug" },
            { "s": "🍻", "t": "bar beer clink drink mug", "d": "clinking beer mugs" },
            { "s": "🥂", "t": "celebrate clink drink glass", "d": "clinking glasses" },
            { "s": "🥃", "t": "glass liquor shot tumbler whisky", "d": "tumbler glass" },
            { "s": "🍽", "t": "cooking fork knife plate", "d": "fork and knife with plate" },
            { "s": "🍴", "t": "cooking fork knife", "d": "fork and knife" },
            { "s": "🥄", "t": "spoon tableware", "d": "spoon" },
            { "s": "🔪", "t": "cooking hocho knife tool weapon", "d": "kitchen knife" },
            { "s": "🏺", "t": "Aquarius cooking drink jug tool weapon zodiac", "d": "amphora" },
            { "s": "🌍", "t": "Africa earth Europe globe world", "d": "globe showing Europe-Africa" },
            { "s": "🌎", "t": "Americas earth globe world", "d": "globe showing Americas" },
            { "s": "🌏", "t": "Asia Australia earth globe world", "d": "globe showing Asia-Australia" },
            { "s": "🌐", "t": "earth globe meridians world", "d": "globe with meridians" },
            { "s": "🗺", "t": "map world", "d": "world map" },
            { "s": "🗾", "t": "Japan map", "d": "map of Japan" },
            { "s": "🏔", "t": "cold mountain snow", "d": "snow-capped mountain" },
            { "s": "⛰", "t": "mountain", "d": "mountain" },
            { "s": "🌋", "t": "eruption mountain", "d": "volcano" },
            { "s": "🗻", "t": "fuji mountain", "d": "mount fuji" },
            { "s": "🏕", "t": "camping", "d": "camping" },
            { "s": "🏖", "t": "beach umbrella", "d": "beach with umbrella" },
            { "s": "🏜", "t": "desert", "d": "desert" },
            { "s": "🏝", "t": "desert island", "d": "desert island" },
            { "s": "🏞", "t": "park", "d": "national park" },
            { "s": "🏟", "t": "stadium", "d": "stadium" },
            { "s": "🏛", "t": "classical", "d": "classical building" },
            { "s": "🏗", "t": "construction", "d": "building construction" },
            { "s": "🏘", "t": "house", "d": "house" },
            { "s": "🏙", "t": "city", "d": "cityscape" },
            { "s": "🏚", "t": "derelict house", "d": "derelict house" },
            { "s": "🏠", "t": "home house", "d": "house" },
            { "s": "🏡", "t": "garden home house", "d": "house with garden" },
            { "s": "🏢", "t": "building", "d": "office building" },
            { "s": "🏣", "t": "Japanese post", "d": "Japanese post office" },
            { "s": "🏤", "t": "European post", "d": "post office" },
            { "s": "🏥", "t": "doctor medicine", "d": "hospital" },
            { "s": "🏦", "t": "building", "d": "bank" },
            { "s": "🏨", "t": "building", "d": "hotel" },
            { "s": "🏩", "t": "hotel love", "d": "love hotel" },
            { "s": "🏪", "t": "convenience store", "d": "convenience store" },
            { "s": "🏫", "t": "building", "d": "school" },
            { "s": "🏬", "t": "department store", "d": "department store" },
            { "s": "🏭", "t": "building", "d": "factory" },
            { "s": "🏯", "t": "castle Japanese", "d": "Japanese castle" },
            { "s": "🏰", "t": "European", "d": "castle" },
            { "s": "💒", "t": "chapel romance", "d": "wedding" },
            { "s": "🗼", "t": "Tokyo tower", "d": "Tokyo tower" },
            { "s": "🗽", "t": "liberty statue", "d": "Statue of Liberty" },
            { "s": "⛪", "t": "Christian cross religion", "d": "church" },
            { "s": "🕌", "t": "islam Muslim religion", "d": "mosque" },
            { "s": "🕍", "t": "Jew Jewish religion temple", "d": "synagogue" },
            { "s": "⛩", "t": "religion shinto shrine", "d": "shinto shrine" },
            { "s": "🕋", "t": "islam Muslim religion", "d": "kaaba" },
            { "s": "⛲", "t": "fountain", "d": "fountain" },
            { "s": "⛺", "t": "camping", "d": "tent" },
            { "s": "🌁", "t": "fog", "d": "foggy" },
            { "s": "🌃", "t": "night star", "d": "night with stars" },
            { "s": "🌄", "t": "morning mountain sun sunrise", "d": "sunrise over mountains" },
            { "s": "🌅", "t": "morning sun", "d": "sunrise" },
            { "s": "🌆", "t": "city dusk evening landscape sun sunset", "d": "cityscape at dusk" },
            { "s": "🌇", "t": "dusk sun", "d": "sunset" },
            { "s": "🌉", "t": "bridge night", "d": "bridge at night" },
            { "s": "♨", "t": "hot hotsprings springs steaming", "d": "hot springs" },
            { "s": "🌌", "t": "space", "d": "milky way" },
            { "s": "🎠", "t": "carousel horse", "d": "carousel horse" },
            { "s": "🎡", "t": "amusement park ferris wheel", "d": "ferris wheel" },
            { "s": "🎢", "t": "amusement park coaster roller", "d": "roller coaster" },
            { "s": "💈", "t": "barber haircut pole", "d": "barber pole" },
            { "s": "🎪", "t": "circus tent", "d": "circus tent" },
            { "s": "🎭", "t": "art mask performing theater theatre", "d": "performing arts" },
            { "s": "🖼", "t": "art frame museum painting picture", "d": "framed picture" },
            { "s": "🎨", "t": "art museum painting palette", "d": "artist palette" },
            { "s": "🎰", "t": "game slot", "d": "slot machine" },
            { "s": "🚂", "t": "engine railway steam train", "d": "locomotive" },
            { "s": "🚃", "t": "car electric railway train tram trolleybus", "d": "railway car" },
            { "s": "🚄", "t": "railway shinkansen speed train", "d": "high-speed train" },
            { "s": "🚅", "t": "bullet railway shinkansen speed train", "d": "high-speed train with bullet nose" },
            { "s": "🚆", "t": "railway", "d": "train" },
            { "s": "🚇", "t": "subway", "d": "metro" },
            { "s": "🚈", "t": "railway", "d": "light rail" },
            { "s": "🚉", "t": "railway train", "d": "station" },
            { "s": "🚊", "t": "trolleybus", "d": "tram" },
            { "s": "🚝", "t": "vehicle", "d": "monorail" },
            { "s": "🚞", "t": "car mountain railway", "d": "mountain railway" },
            { "s": "🚋", "t": "car tram trolleybus", "d": "tram car" },
            { "s": "🚌", "t": "vehicle", "d": "bus" },
            { "s": "🚍", "t": "bus oncoming", "d": "oncoming bus" },
            { "s": "🚎", "t": "bus tram trolley", "d": "trolleybus" },
            { "s": "🚐", "t": "bus", "d": "minibus" },
            { "s": "🚑", "t": "vehicle", "d": "ambulance" },
            { "s": "🚒", "t": "engine fire truck", "d": "fire engine" },
            { "s": "🚓", "t": "car patrol police", "d": "police car" },
            { "s": "🚔", "t": "car oncoming police", "d": "oncoming police car" },
            { "s": "🚕", "t": "vehicle", "d": "taxi" },
            { "s": "🚖", "t": "oncoming taxi", "d": "oncoming taxi" },
            { "s": "🚗", "t": "car", "d": "automobile" },
            { "s": "🚘", "t": "automobile car oncoming", "d": "oncoming automobile" },
            { "s": "🚙", "t": "recreational sport utility", "d": "sport utility vehicle" },
            { "s": "🚚", "t": "delivery truck", "d": "delivery truck" },
            { "s": "🚛", "t": "lorry semi truck", "d": "articulated lorry" },
            { "s": "🚜", "t": "vehicle", "d": "tractor" },
            { "s": "🚲", "t": "bike", "d": "bicycle" },
            { "s": "🛴", "t": "kick scooter", "d": "kick scooter" },
            { "s": "🛵", "t": "motor scooter", "d": "motor scooter" },
            { "s": "🚏", "t": "bus busstop stop", "d": "bus stop" },
            { "s": "🛣", "t": "highway road", "d": "motorway" },
            { "s": "🛤", "t": "railway train", "d": "railway track" },
            { "s": "⛽", "t": "fuel fuelpump gas pump station", "d": "fuel pump" },
            { "s": "🚨", "t": "beacon car light police revolving", "d": "police car light" },
            { "s": "🚥", "t": "light signal traffic", "d": "horizontal traffic light" },
            { "s": "🚦", "t": "light signal traffic", "d": "vertical traffic light" },
            { "s": "🚧", "t": "barrier", "d": "construction" },
            { "s": "🛑", "t": "octagonal sign stop", "d": "stop sign" },
            { "s": "⚓", "t": "ship tool", "d": "anchor" },
            { "s": "⛵", "t": "boat resort sea yacht", "d": "sailboat" },
            { "s": "🛶", "t": "boat canoe", "d": "canoe" },
            { "s": "🚤", "t": "boat", "d": "speedboat" },
            { "s": "🛳", "t": "passenger ship", "d": "passenger ship" },
            { "s": "⛴", "t": "boat passenger", "d": "ferry" },
            { "s": "🛥", "t": "boat motorboat", "d": "motor boat" },
            { "s": "🚢", "t": "boat passenger", "d": "ship" },
            { "s": "✈", "t": "aeroplane airplane", "d": "airplane" },
            { "s": "🛩", "t": "aeroplane airplane", "d": "small airplane" },
            { "s": "🛫", "t": "aeroplane airplane check-in departure departures", "d": "airplane departure" },
            { "s": "🛬", "t": "aeroplane airplane arrivals arriving landing", "d": "airplane arrival" },
            { "s": "💺", "t": "chair", "d": "seat" },
            { "s": "🚁", "t": "vehicle", "d": "helicopter" },
            { "s": "🚟", "t": "railway suspension", "d": "suspension railway" },
            { "s": "🚠", "t": "cable gondola mountain", "d": "mountain cableway" },
            { "s": "🚡", "t": "aerial cable car gondola tramway", "d": "aerial tramway" },
            { "s": "🛰", "t": "space", "d": "satellite" },
            { "s": "🚀", "t": "space", "d": "rocket" },
            /*
            { "s": "🛎", "t": "bell bellhop hotel", "d": "bellhop bell" },
            { "s": "🚪", "t": "door", "d": "door" },
            { "s": "🛏", "t": "hotel sleep", "d": "bed" },
            { "s": "🛋", "t": "couch hotel lamp", "d": "couch and lamp" },
            */
            { "s": "🚽", "t": "toilet", "d": "toilet" },
            { "s": "🚿", "t": "water", "d": "shower" },
            { "s": "🛁", "t": "bath", "d": "bathtub" },
            { "s": "⌛", "t": "sand timer", "d": "hourglass" },
            { "s": "⏳", "t": "hourglass sand timer", "d": "hourglass with flowing sand" },
            { "s": "⌚", "t": "clock", "d": "watch" },
            { "s": "⏰", "t": "alarm clock", "d": "alarm clock" },
            /*
            { "s": "⏱", "t": "clock", "d": "stopwatch" },
            { "s": "⏲", "t": "clock timer", "d": "timer clock" },
            { "s": "🕰", "t": "clock", "d": "mantelpiece clock" },
            { "s": "🕛", "t": "00 12 12:00 clock o’clock twelve", "d": "twelve o’clock" },
            { "s": "🕧", "t": "12 12:30 30 clock thirty twelve", "d": "twelve-thirty" },
            { "s": "🕐", "t": "00 1 1:00 clock o’clock one", "d": "one o’clock" },
            { "s": "🕜", "t": "1 1:30 30 clock one thirty", "d": "one-thirty" },
            { "s": "🕑", "t": "00 2 2:00 clock o’clock two", "d": "two o’clock" },
            { "s": "🕝", "t": "2 2:30 30 clock thirty two", "d": "two-thirty" },
            { "s": "🕒", "t": "00 3 3:00 clock o’clock three", "d": "three o’clock" },
            { "s": "🕞", "t": "3 3:30 30 clock thirty three", "d": "three-thirty" },
            { "s": "🕓", "t": "00 4 4:00 clock four o’clock", "d": "four o’clock" },
            { "s": "🕟", "t": "30 4 4:30 clock four thirty", "d": "four-thirty" },
            { "s": "🕔", "t": "00 5 5:00 clock five o’clock", "d": "five o’clock" },
            { "s": "🕠", "t": "30 5 5:30 clock five thirty", "d": "five-thirty" },
            { "s": "🕕", "t": "00 6 6:00 clock o’clock six", "d": "six o’clock" },
            { "s": "🕡", "t": "30 6 6:30 clock six thirty", "d": "six-thirty" },
            { "s": "🕖", "t": "00 7 7:00 clock o’clock seven", "d": "seven o’clock" },
            { "s": "🕢", "t": "30 7 7:30 clock seven thirty", "d": "seven-thirty" },
            { "s": "🕗", "t": "00 8 8:00 clock eight o’clock", "d": "eight o’clock" },
            { "s": "🕣", "t": "30 8 8:30 clock eight thirty", "d": "eight-thirty" },
            { "s": "🕘", "t": "00 9 9:00 clock nine o’clock", "d": "nine o’clock" },
            { "s": "🕤", "t": "30 9 9:30 clock nine thirty", "d": "nine-thirty" },
            { "s": "🕙", "t": "00 10 10:00 clock o’clock ten", "d": "ten o’clock" },
            { "s": "🕥", "t": "10 10:30 30 clock ten thirty", "d": "ten-thirty" },
            { "s": "🕚", "t": "00 11 11:00 clock eleven o’clock", "d": "eleven o’clock" },
            { "s": "🕦", "t": "11 11:30 30 clock eleven thirty", "d": "eleven-thirty" },
            */
            { "s": "🌑", "t": "dark moon", "d": "new moon" },
            { "s": "🌒", "t": "crescent moon waxing", "d": "waxing crescent moon" },
            { "s": "🌓", "t": "moon quarter", "d": "first quarter moon" },
            { "s": "🌔", "t": "gibbous moon waxing", "d": "waxing gibbous moon" },
            { "s": "🌕", "t": "full moon", "d": "full moon" },
            { "s": "🌖", "t": "gibbous moon waning", "d": "waning gibbous moon" },
            { "s": "🌗", "t": "moon quarter", "d": "last quarter moon" },
            { "s": "🌘", "t": "crescent moon waning", "d": "waning crescent moon" },
            { "s": "🌙", "t": "crescent moon", "d": "crescent moon" },
            { "s": "🌚", "t": "face moon", "d": "new moon face" },
            { "s": "🌛", "t": "face moon quarter", "d": "first quarter moon with face" },
            { "s": "🌜", "t": "face moon quarter", "d": "last quarter moon with face" },
            { "s": "🌡", "t": "weather", "d": "thermometer" },
            { "s": "☀", "t": "bright rays sunny", "d": "sun" },
            { "s": "🌝", "t": "bright face full moon", "d": "full moon with face" },
            { "s": "🌞", "t": "bright face sun", "d": "sun with face" },
            { "s": "⭐", "t": "star", "d": "white medium star" },
            { "s": "🌟", "t": "glittery glow shining sparkle star", "d": "glowing star" },
            /*
            { "s": "🌠", "t": "falling shooting star", "d": "shooting star" },
            { "s": "☁", "t": "weather", "d": "cloud" },
            { "s": "⛅", "t": "cloud sun", "d": "sun behind cloud" },
            { "s": "⛈", "t": "cloud rain thunder", "d": "cloud with lightning and rain" },
            { "s": "🌤", "t": "cloud sun", "d": "sun behind small cloud" },
            { "s": "🌥", "t": "cloud sun", "d": "sun behind large cloud" },
            { "s": "🌦", "t": "cloud rain sun", "d": "sun behind rain cloud" },
            { "s": "🌧", "t": "cloud rain", "d": "cloud with rain" },
            { "s": "🌨", "t": "cloud cold snow", "d": "cloud with snow" },
            { "s": "🌩", "t": "cloud lightning", "d": "cloud with lightning" },
            { "s": "🌪", "t": "cloud whirlwind", "d": "tornado" },
            { "s": "🌫", "t": "cloud", "d": "fog" },
            { "s": "🌬", "t": "blow cloud face wind", "d": "wind face" },
            { "s": "🌀", "t": "dizzy twister typhoon", "d": "cyclone" },
            { "s": "🌈", "t": "rain", "d": "rainbow" },
            { "s": "🌂", "t": "clothing rain umbrella", "d": "closed umbrella" },
            { "s": "☂", "t": "clothing rain", "d": "umbrella" },
            { "s": "☔", "t": "clothing drop rain umbrella", "d": "umbrella with rain drops" },
            { "s": "⛱", "t": "rain sun umbrella", "d": "umbrella on ground" },
            { "s": "⚡", "t": "danger electric electricity lightning voltage zap", "d": "high voltage" },
            { "s": "❄", "t": "cold snow", "d": "snowflake" },
            { "s": "☃", "t": "cold snow", "d": "snowman" },
            */
            { "s": "⛄", "t": "cold snow snowman", "d": "snowman without snow" },
            { "s": "☄", "t": "space", "d": "comet" },
            { "s": "🔥", "t": "flame tool", "d": "fire" },
            { "s": "💧", "t": "cold comic drop sweat", "d": "droplet" },
            { "s": "🌊", "t": "ocean water wave", "d": "water wave" },
            { "s": "🎃", "t": "celebration halloween jack lantern", "d": "jack-o-lantern" },
            { "s": "🎄", "t": "celebration Christmas tree", "d": "Christmas tree" },
            { "s": "🎆", "t": "celebration", "d": "fireworks" },
            { "s": "🎇", "t": "celebration fireworks sparkle", "d": "sparkler" },
            { "s": "✨", "t": "sparkle star", "d": "sparkles" },
            { "s": "🎈", "t": "celebration", "d": "balloon" },
            { "s": "🎉", "t": "celebration party popper tada", "d": "party popper" },
            { "s": "🎊", "t": "ball celebration confetti", "d": "confetti ball" },
            { "s": "🎋", "t": "banner celebration Japanese tree", "d": "tanabata tree" },
            { "s": "🎍", "t": "bamboo celebration Japanese pine", "d": "pine decoration" },
            { "s": "🎎", "t": "celebration doll festival Japanese", "d": "Japanese dolls" },
            { "s": "🎏", "t": "carp celebration streamer", "d": "carp streamer" },
            { "s": "🎐", "t": "bell celebration chime wind", "d": "wind chime" },
            { "s": "🎑", "t": "celebration ceremony moon", "d": "moon viewing ceremony" },
            { "s": "🎀", "t": "celebration", "d": "ribbon" },
            { "s": "🎁", "t": "box celebration gift present wrapped", "d": "wrapped gift" },
            { "s": "🎗", "t": "celebration reminder ribbon", "d": "reminder ribbon" },
            { "s": "🎟", "t": "admission ticket", "d": "admission tickets" },
            { "s": "🎫", "t": "admission", "d": "ticket" },
            { "s": "🎖", "t": "celebration medal military", "d": "military medal" },
            { "s": "🏆", "t": "prize", "d": "trophy" },
            { "s": "🏅", "t": "medal", "d": "sports medal" },
            { "s": "🥇", "t": "first gold medal", "d": "1st place medal" },
            { "s": "🥈", "t": "medal second silver", "d": "2nd place medal" },
            { "s": "🥉", "t": "bronze medal third", "d": "3rd place medal" },
            { "s": "⚽", "t": "ball football soccer", "d": "soccer ball" },
            { "s": "⚾", "t": "ball", "d": "baseball" },
            { "s": "🏀", "t": "ball hoop", "d": "basketball" },
            { "s": "🏐", "t": "ball game", "d": "volleyball" },
            { "s": "🏈", "t": "american ball football", "d": "american football" },
            { "s": "🏉", "t": "ball football rugby", "d": "rugby football" },
            { "s": "🎾", "t": "ball racquet", "d": "tennis" },
            { "s": "🎱", "t": "8 8 ball ball billiard eight game", "d": "pool 8 ball" },
            { "s": "🎳", "t": "ball game", "d": "bowling" },
            { "s": "🏏", "t": "ball bat game", "d": "cricket" },
            { "s": "🏑", "t": "ball field game hockey stick", "d": "field hockey" },
            { "s": "🏒", "t": "game hockey ice puck stick", "d": "ice hockey" },
            { "s": "🏓", "t": "ball bat game paddle ping pong table tennis", "d": "ping pong" },
            { "s": "🏸", "t": "birdie game racquet shuttlecock", "d": "badminton" },
            { "s": "🥊", "t": "boxing glove", "d": "boxing glove" },
            { "s": "🥋", "t": "judo karate martial arts taekwondo uniform", "d": "martial arts uniform" },
            { "s": "🥅", "t": "goal net", "d": "goal net" },
            { "s": "🎯", "t": "bull bullseye dart eye game hit target", "d": "direct hit" },
            { "s": "⛳", "t": "golf hole", "d": "flag in hole" },
            { "s": "⛸", "t": "ice skate", "d": "ice skate" },
            { "s": "🎣", "t": "fish pole", "d": "fishing pole" },
            { "s": "🎽", "t": "athletics running sash shirt", "d": "running shirt" },
            { "s": "🎿", "t": "ski snow", "d": "skis" },
            { "s": "🎮", "t": "controller game", "d": "video game" },
            /*
            { "s": "🕹", "t": "game video game", "d": "joystick" },
            { "s": "🎲", "t": "dice die game", "d": "game die" },
            { "s": "♠", "t": "card game", "d": "spade suit" },
            { "s": "♥", "t": "card game", "d": "heart suit" },
            { "s": "♦", "t": "card game", "d": "diamond suit" },
            { "s": "♣", "t": "card game", "d": "club suit" },
            { "s": "🃏", "t": "card game wildcard", "d": "joker" },
            { "s": "🀄", "t": "game mahjong red", "d": "mahjong red dragon" },
            { "s": "🎴", "t": "card flower game Japanese playing", "d": "flower playing cards" },
            { "s": "🔇", "t": "mute quiet silent speaker", "d": "muted speaker" },
            { "s": "🔈", "t": "soft", "d": "speaker low volume" },
            { "s": "🔉", "t": "medium", "d": "speaker medium volume" },
            { "s": "🔊", "t": "loud", "d": "speaker high volume" },
            { "s": "📢", "t": "loud public address", "d": "loudspeaker" },
            { "s": "📣", "t": "cheering", "d": "megaphone" },
            { "s": "📯", "t": "horn post postal", "d": "postal horn" },
            { "s": "🔔", "t": "bell", "d": "bell" },
            { "s": "🔕", "t": "bell forbidden mute no not prohibited quiet silent", "d": "bell with slash" },
            { "s": "🎼", "t": "music score", "d": "musical score" },
            { "s": "🎵", "t": "music note", "d": "musical note" },
            { "s": "🎶", "t": "music note notes", "d": "musical notes" },
            { "s": "🎙", "t": "mic microphone music studio", "d": "studio microphone" },
            { "s": "🎚", "t": "level music slider", "d": "level slider" },
            { "s": "🎛", "t": "control knobs music", "d": "control knobs" },
            { "s": "🎤", "t": "karaoke mic", "d": "microphone" },
            { "s": "🎧", "t": "earbud", "d": "headphone" },
            { "s": "📻", "t": "video", "d": "radio" },
            */
            { "s": "🎸", "t": "instrument music", "d": "guitar" },
            { "s": "🎹", "t": "instrument keyboard music piano", "d": "musical keyboard" },
            { "s": "🎺", "t": "instrument music", "d": "trumpet" },
            { "s": "🎻", "t": "instrument music", "d": "violin" },
            { "s": "🥁", "t": "drum drumsticks music", "d": "drum" },
            /*
            { "s": "📱", "t": "cell mobile phone telephone", "d": "mobile phone" },
            { "s": "📲", "t": "arrow call cell mobile phone receive telephone", "d": "mobile phone with arrow" },
            { "s": "☎", "t": "phone", "d": "telephone" },
            { "s": "📞", "t": "phone receiver telephone", "d": "telephone receiver" },
            { "s": "📟", "t": "pager", "d": "pager" },
            { "s": "📠", "t": "fax", "d": "fax machine" },
            { "s": "🔋", "t": "battery", "d": "battery" },
            { "s": "🔌", "t": "electric electricity plug", "d": "electric plug" },
            { "s": "💻", "t": "computer pc personal", "d": "laptop computer" },
            { "s": "🖥", "t": "computer desktop", "d": "desktop computer" },
            { "s": "🖨", "t": "computer", "d": "printer" },
            { "s": "⌨", "t": "computer", "d": "keyboard" },
            { "s": "🖱", "t": "computer", "d": "computer mouse" },
            { "s": "🖲", "t": "computer", "d": "trackball" },
            { "s": "💽", "t": "computer disk minidisk optical", "d": "computer disk" },
            { "s": "💾", "t": "computer disk floppy", "d": "floppy disk" },
            { "s": "💿", "t": "cd computer disk optical", "d": "optical disk" },
            { "s": "📀", "t": "blu-ray computer disk dvd optical", "d": "dvd" },
            { "s": "🎥", "t": "camera cinema movie", "d": "movie camera" },
            { "s": "🎞", "t": "cinema film frames movie", "d": "film frames" },
            { "s": "📽", "t": "cinema film movie projector video", "d": "film projector" },
            */
            { "s": "🎬", "t": "clapper movie", "d": "clapper board" },
            { "s": "📺", "t": "tv video", "d": "television" },
            { "s": "📷", "t": "video", "d": "camera" },
            { "s": "📸", "t": "camera flash video", "d": "camera with flash" },
            /*
            { "s": "📹", "t": "camera video", "d": "video camera" },
            { "s": "📼", "t": "tape vhs video", "d": "videocassette" },
            { "s": "🔍", "t": "glass magnifying search tool", "d": "left-pointing magnifying glass" },
            { "s": "🔎", "t": "glass magnifying search tool", "d": "right-pointing magnifying glass" },
            { "s": "🔬", "t": "science tool", "d": "microscope" },
            { "s": "🔭", "t": "science tool", "d": "telescope" },
            { "s": "📡", "t": "antenna dish satellite", "d": "satellite antenna" },
            { "s": "🕯", "t": "light", "d": "candle" },
            { "s": "💡", "t": "bulb comic electric idea light", "d": "light bulb" },
            { "s": "🔦", "t": "electric light tool torch", "d": "flashlight" },
            { "s": "🏮", "t": "bar lantern light red", "d": "red paper lantern" },
            { "s": "📔", "t": "book cover decorated notebook", "d": "notebook with decorative cover" },
            { "s": "📕", "t": "book closed", "d": "closed book" },
            { "s": "📖", "t": "book open", "d": "open book" },
            { "s": "📗", "t": "book green", "d": "green book" },
            { "s": "📘", "t": "blue book", "d": "blue book" },
            { "s": "📙", "t": "book orange", "d": "orange book" },
            { "s": "📚", "t": "book", "d": "books" },
            { "s": "📓", "t": "notebook", "d": "notebook" },
            { "s": "📒", "t": "notebook", "d": "ledger" },
            { "s": "📃", "t": "curl document page", "d": "page with curl" },
            { "s": "📜", "t": "paper", "d": "scroll" },
            { "s": "📄", "t": "document page", "d": "page facing up" },
            { "s": "📰", "t": "news paper", "d": "newspaper" },
            { "s": "🗞", "t": "news newspaper paper rolled", "d": "rolled-up newspaper" },
            { "s": "📑", "t": "bookmark mark marker tabs", "d": "bookmark tabs" },
            { "s": "🔖", "t": "mark", "d": "bookmark" },
            { "s": "🏷", "t": "label", "d": "label" },
            { "s": "💰", "t": "bag dollar money moneybag", "d": "money bag" },
            { "s": "💴", "t": "bank banknote bill currency money note yen", "d": "yen banknote" },
            { "s": "💵", "t": "bank banknote bill currency dollar money note", "d": "dollar banknote" },
            { "s": "💶", "t": "bank banknote bill currency euro money note", "d": "euro banknote" },
            { "s": "💷", "t": "bank banknote bill currency money note pound", "d": "pound banknote" },
            { "s": "💸", "t": "bank banknote bill dollar fly money note wings", "d": "money with wings" },
            { "s": "💳", "t": "bank card credit money", "d": "credit card" },
            { "s": "💹", "t": "bank chart currency graph growth market money rise trend upward yen", "d": "chart increasing with yen" },
            { "s": "💱", "t": "bank currency exchange money", "d": "currency exchange" },
            { "s": "💲", "t": "currency dollar money", "d": "heavy dollar sign" },
            { "s": "✉", "t": "email letter", "d": "envelope" },
            { "s": "📧", "t": "email letter mail", "d": "e-mail" },
            { "s": "📨", "t": "e-mail email envelope incoming letter mail receive", "d": "incoming envelope" },
            { "s": "📩", "t": "arrow down e-mail email envelope letter mail outgoing sent", "d": "envelope with arrow" },
            { "s": "📤", "t": "box letter mail outbox sent tray", "d": "outbox tray" },
            { "s": "📥", "t": "box inbox letter mail receive tray", "d": "inbox tray" },
            { "s": "📦", "t": "box parcel", "d": "package" },
            { "s": "📫", "t": "closed mail mailbox postbox", "d": "closed mailbox with raised flag" },
            { "s": "📪", "t": "closed lowered mail mailbox postbox", "d": "closed mailbox with lowered flag" },
            { "s": "📬", "t": "mail mailbox open postbox", "d": "open mailbox with raised flag" },
            { "s": "📭", "t": "lowered mail mailbox open postbox", "d": "open mailbox with lowered flag" },
            { "s": "📮", "t": "mail mailbox", "d": "postbox" },
            { "s": "🗳", "t": "ballot box", "d": "ballot box with ballot" },
            { "s": "✏", "t": "pencil", "d": "pencil" },
            { "s": "✒", "t": "nib pen", "d": "black nib" },
            { "s": "🖋", "t": "fountain pen", "d": "fountain pen" },
            { "s": "🖊", "t": "ballpoint", "d": "pen" },
            { "s": "🖌", "t": "painting", "d": "paintbrush" },
            { "s": "🖍", "t": "crayon", "d": "crayon" },
            { "s": "📝", "t": "pencil", "d": "memo" },
            { "s": "💼", "t": "briefcase", "d": "briefcase" },
            { "s": "📁", "t": "file folder", "d": "file folder" },
            { "s": "📂", "t": "file folder open", "d": "open file folder" },
            { "s": "🗂", "t": "card dividers index", "d": "card index dividers" },
            */
            { "s": "📅", "t": "date", "d": "calendar" },
            { "s": "📆", "t": "calendar", "d": "tear-off calendar" },
            /*
            { "s": "🗒", "t": "note pad spiral", "d": "spiral notepad" },
            { "s": "🗓", "t": "calendar pad spiral", "d": "spiral calendar" },
            { "s": "📇", "t": "card index rolodex", "d": "card index" },
            { "s": "📈", "t": "chart graph growth trend upward", "d": "chart increasing" },
            { "s": "📉", "t": "chart down graph trend", "d": "chart decreasing" },
            { "s": "📊", "t": "bar chart graph", "d": "bar chart" },
            { "s": "📋", "t": "clipboard", "d": "clipboard" },
            { "s": "📌", "t": "pin", "d": "pushpin" },
            { "s": "📍", "t": "pin pushpin", "d": "round pushpin" },
            { "s": "📎", "t": "paperclip", "d": "paperclip" },
            { "s": "🖇", "t": "link paperclip", "d": "linked paperclips" },
            { "s": "📏", "t": "ruler straight edge", "d": "straight ruler" },
            { "s": "📐", "t": "ruler set triangle", "d": "triangular ruler" },
            { "s": "✂", "t": "cutting tool", "d": "scissors" },
            { "s": "🗃", "t": "box card file", "d": "card file box" },
            { "s": "🗄", "t": "cabinet file filing", "d": "file cabinet" },
            { "s": "🗑", "t": "wastebasket", "d": "wastebasket" },
            { "s": "🔒", "t": "closed", "d": "locked" },
            { "s": "🔓", "t": "lock open unlock", "d": "unlocked" },
            { "s": "🔏", "t": "ink lock nib pen privacy", "d": "locked with pen" },
            { "s": "🔐", "t": "closed key lock secure", "d": "locked with key" },
            */
            { "s": "🔑", "t": "lock password", "d": "key" },
            /*
            { "s": "🗝", "t": "clue key lock old", "d": "old key" },
            */
            { "s": "🔨", "t": "tool", "d": "hammer" },
            /*
            { "s": "⛏", "t": "mining tool", "d": "pick" },
            { "s": "⚒", "t": "hammer pick tool", "d": "hammer and pick" },
            { "s": "🛠", "t": "hammer spanner tool wrench", "d": "hammer and wrench" },
            { "s": "🗡", "t": "knife weapon", "d": "dagger" },
            { "s": "⚔", "t": "crossed swords weapon", "d": "crossed swords" },
            { "s": "🔫", "t": "gun handgun revolver tool weapon", "d": "pistol" },
            { "s": "🏹", "t": "archer archery arrow bow Sagittarius tool weapon zodiac", "d": "bow and arrow" },
            { "s": "🛡", "t": "weapon", "d": "shield" },
            { "s": "🔧", "t": "spanner tool wrench", "d": "wrench" },
            { "s": "🔩", "t": "bolt nut tool", "d": "nut and bolt" },
            { "s": "⚙", "t": "tool", "d": "gear" },
            { "s": "🗜", "t": "compress tool vice", "d": "clamp" },
            { "s": "⚗", "t": "chemistry tool", "d": "alembic" },
            { "s": "⚖", "t": "balance justice Libra scales tool weight zodiac", "d": "balance scale" },
            { "s": "🔗", "t": "link", "d": "link" },
            { "s": "⛓", "t": "chain", "d": "chains" },
            */
            { "s": "💉", "t": "doctor medicine needle shot sick tool", "d": "syringe" },
            { "s": "💊", "t": "doctor medicine sick", "d": "pill" },
            { "s": "🚬", "t": "smoking", "d": "cigarette" },
            /*
            { "s": "⚰", "t": "death", "d": "coffin" },
            { "s": "⚱", "t": "ashes death funeral urn", "d": "funeral urn" },
            { "s": "🗿", "t": "face moyai statue", "d": "moai" },
            { "s": "🛢", "t": "drum oil", "d": "oil drum" },
            { "s": "🔮", "t": "ball crystal fairy tale fantasy fortune tool", "d": "crystal ball" },
            { "s": "🛒", "t": "cart shopping trolley", "d": "shopping cart" },
            { "s": "🏧", "t": "atm automated bank teller", "d": "ATM sign" },
            { "s": "🚮", "t": "litter litter bin", "d": "litter in bin sign" },
            { "s": "🚰", "t": "drinking potable water", "d": "potable water" },
            { "s": "♿", "t": "access", "d": "wheelchair symbol" },
            { "s": "🚹", "t": "lavatory man restroom wc", "d": "men’s room" },
            { "s": "🚺", "t": "lavatory restroom wc woman", "d": "women’s room" },
            { "s": "🚻", "t": "lavatory restroom WC", "d": "restroom" },
            { "s": "🚼", "t": "baby changing", "d": "baby symbol" },
            { "s": "🚾", "t": "closet lavatory restroom water wc", "d": "water closet" },
            { "s": "🛂", "t": "control passport", "d": "passport control" },
            { "s": "🛃", "t": "customs", "d": "customs" },
            { "s": "🛄", "t": "baggage claim", "d": "baggage claim" },
            { "s": "🛅", "t": "baggage locker luggage", "d": "left luggage" },
            { "s": "⚠", "t": "warning", "d": "warning" },
            { "s": "🚸", "t": "child crossing pedestrian traffic", "d": "children crossing" },
            { "s": "⛔", "t": "entry forbidden no not prohibited traffic", "d": "no entry" },
            { "s": "🚫", "t": "entry forbidden no not", "d": "prohibited" },
            { "s": "🚳", "t": "bicycle bike forbidden no not prohibited", "d": "no bicycles" },
            { "s": "🚭", "t": "forbidden no not prohibited smoking", "d": "no smoking" },
            { "s": "🚯", "t": "forbidden litter no not prohibited", "d": "no littering" },
            { "s": "🚱", "t": "non-drinking non-potable water", "d": "non-potable water" },
            { "s": "🚷", "t": "forbidden no not pedestrian prohibited", "d": "no pedestrians" },
            { "s": "📵", "t": "cell forbidden mobile no not phone prohibited telephone", "d": "no mobile phones" },
            { "s": "🔞", "t": "18 age restriction eighteen forbidden no not prohibited underage", "d": "no one under eighteen" },
            { "s": "☢", "t": "radioactive sign", "d": "radioactive" },
            { "s": "☣", "t": "biohazard sign", "d": "biohazard" },
            { "s": "⬆", "t": "arrow cardinal direction north", "d": "up arrow" },
            { "s": "↗", "t": "arrow direction intercardinal northeast", "d": "up-right arrow" },
            { "s": "➡", "t": "arrow cardinal direction east", "d": "right arrow" },
            { "s": "↘", "t": "arrow direction intercardinal southeast", "d": "down-right arrow" },
            { "s": "⬇", "t": "arrow cardinal direction down south", "d": "down arrow" },
            { "s": "↙", "t": "arrow direction intercardinal southwest", "d": "down-left arrow" },
            { "s": "⬅", "t": "arrow cardinal direction west", "d": "left arrow" },
            { "s": "↖", "t": "arrow direction intercardinal northwest", "d": "up-left arrow" },
            { "s": "↕", "t": "arrow", "d": "up-down arrow" },
            { "s": "↔", "t": "arrow", "d": "left-right arrow" },
            { "s": "↩", "t": "arrow", "d": "right arrow curving left" },
            { "s": "↪", "t": "arrow", "d": "left arrow curving right" },
            { "s": "⤴", "t": "arrow", "d": "right arrow curving up" },
            { "s": "⤵", "t": "arrow down", "d": "right arrow curving down" },
            { "s": "🔃", "t": "arrow clockwise reload", "d": "clockwise vertical arrows" },
            { "s": "🔄", "t": "anticlockwise arrow counterclockwise withershins", "d": "anticlockwise arrows button" },
            { "s": "🔙", "t": "arrow back", "d": "BACK arrow" },
            { "s": "🔚", "t": "arrow end", "d": "END arrow" },
            { "s": "🔛", "t": "arrow mark on", "d": "ON! arrow" },
            { "s": "🔜", "t": "arrow soon", "d": "SOON arrow" },
            { "s": "🔝", "t": "arrow top up", "d": "TOP arrow" },
            { "s": "🛐", "t": "religion worship", "d": "place of worship" },
            { "s": "⚛", "t": "atheist atom", "d": "atom symbol" },
            { "s": "🕉", "t": "Hindu religion", "d": "om" },
            { "s": "✡", "t": "David Jew Jewish religion star", "d": "star of David" },
            { "s": "☸", "t": "Buddhist dharma religion wheel", "d": "wheel of dharma" },
            { "s": "☯", "t": "religion tao taoist yang yin", "d": "yin yang" },
            { "s": "✝", "t": "Christian cross religion", "d": "latin cross" },
            { "s": "☦", "t": "Christian cross religion", "d": "orthodox cross" },
            { "s": "☪", "t": "islam Muslim religion", "d": "star and crescent" },
            { "s": "☮", "t": "peace", "d": "peace symbol" },
            { "s": "🕎", "t": "candelabrum candlestick religion", "d": "menorah" },
            { "s": "🔯", "t": "fortune star", "d": "dotted six-pointed star" },
            { "s": "♈", "t": "ram zodiac", "d": "Aries" },
            { "s": "♉", "t": "bull ox zodiac", "d": "Taurus" },
            { "s": "♊", "t": "twins zodiac", "d": "Gemini" },
            { "s": "♋", "t": "crab zodiac", "d": "Cancer" },
            { "s": "♌", "t": "lion zodiac", "d": "Leo" },
            { "s": "♍", "t": "zodiac", "d": "Virgo" },
            { "s": "♎", "t": "balance justice scales zodiac", "d": "Libra" },
            { "s": "♏", "t": "scorpio scorpion zodiac", "d": "Scorpius" },
            { "s": "♐", "t": "archer zodiac", "d": "Sagittarius" },
            { "s": "♑", "t": "goat zodiac", "d": "Capricorn" },
            { "s": "♒", "t": "bearer water zodiac", "d": "Aquarius" },
            { "s": "♓", "t": "fish zodiac", "d": "Pisces" },
            { "s": "⛎", "t": "bearer serpent snake zodiac", "d": "Ophiuchus" },
            { "s": "🔀", "t": "arrow crossed", "d": "shuffle tracks button" },
            { "s": "🔁", "t": "arrow clockwise repeat", "d": "repeat button" },
            { "s": "🔂", "t": "arrow clockwise once", "d": "repeat single button" },
            { "s": "▶", "t": "arrow play right triangle", "d": "play button" },
            { "s": "⏩", "t": "arrow double fast forward", "d": "fast-forward button" },
            { "s": "⏭", "t": "arrow next scene next track triangle", "d": "next track button" },
            { "s": "⏯", "t": "arrow pause play right triangle", "d": "play or pause button" },
            { "s": "◀", "t": "arrow left reverse triangle", "d": "reverse button" },
            { "s": "⏪", "t": "arrow double rewind", "d": "fast reverse button" },
            { "s": "⏮", "t": "arrow previous scene previous track triangle", "d": "last track button" },
            { "s": "🔼", "t": "arrow button red", "d": "up button" },
            { "s": "⏫", "t": "arrow double", "d": "fast up button" },
            { "s": "🔽", "t": "arrow button down red", "d": "down button" },
            { "s": "⏬", "t": "arrow double down", "d": "fast down button" },
            { "s": "⏸", "t": "bar double pause vertical", "d": "pause button" },
            { "s": "⏹", "t": "square stop", "d": "stop button" },
            { "s": "⏺", "t": "circle record", "d": "record button" },
            { "s": "⏏", "t": "eject", "d": "eject button" },
            { "s": "🎦", "t": "camera film movie", "d": "cinema" },
            { "s": "🔅", "t": "brightness dim low", "d": "dim button" },
            { "s": "🔆", "t": "bright brightness", "d": "bright button" },
            { "s": "📶", "t": "antenna bar cell mobile phone signal telephone", "d": "antenna bars" },
            { "s": "📳", "t": "cell mobile mode phone telephone vibration", "d": "vibration mode" },
            { "s": "📴", "t": "cell mobile off phone telephone", "d": "mobile phone off" },
            { "s": "♀", "t": "woman", "d": "female sign" },
            { "s": "♂", "t": "man", "d": "male sign" },
            { "s": "⚕", "t": "aesculapius medicine staff", "d": "medical symbol" },
            { "s": "♻", "t": "recycle", "d": "recycling symbol" },
            { "s": "⚜", "t": "fleur-de-lis", "d": "fleur-de-lis" },
            { "s": "🔱", "t": "anchor emblem ship tool trident", "d": "trident emblem" },
            { "s": "📛", "t": "badge name", "d": "name badge" },
            { "s": "🔰", "t": "beginner chevron green Japanese leaf tool yellow", "d": "Japanese symbol for beginner" },
            { "s": "⭕", "t": "circle o", "d": "heavy large circle" },
            { "s": "✅", "t": "check mark", "d": "white heavy check mark" },
            { "s": "☑", "t": "ballot box check", "d": "ballot box with check" },
            { "s": "✔", "t": "check mark", "d": "heavy check mark" },
            { "s": "✖", "t": "cancel multiplication multiply x", "d": "heavy multiplication x" },
            { "s": "❌", "t": "cancel mark multiplication multiply x", "d": "cross mark" },
            { "s": "❎", "t": "mark square", "d": "cross mark button" },
            { "s": "➕", "t": "math plus", "d": "heavy plus sign" },
            { "s": "➖", "t": "math minus", "d": "heavy minus sign" },
            { "s": "➗", "t": "division math", "d": "heavy division sign" },
            { "s": "➰", "t": "curl loop", "d": "curly loop" },
            { "s": "➿", "t": "curl double loop", "d": "double curly loop" },
            { "s": "〽", "t": "mark part", "d": "part alternation mark" },
            { "s": "✳", "t": "asterisk", "d": "eight-spoked asterisk" },
            { "s": "✴", "t": "star", "d": "eight-pointed star" },
            { "s": "❇", "t": "sparkle", "d": "sparkle" },
            { "s": "‼", "t": "bangbang exclamation mark punctuation", "d": "double exclamation mark" },
            { "s": "⁉", "t": "exclamation interrobang mark punctuation question", "d": "exclamation question mark" },
            { "s": "❓", "t": "mark punctuation question", "d": "question mark" },
            { "s": "❔", "t": "mark outlined punctuation question", "d": "white question mark" },
            { "s": "❕", "t": "exclamation mark outlined punctuation", "d": "white exclamation mark" },
            { "s": "❗", "t": "exclamation mark punctuation", "d": "exclamation mark" },
            { "s": "〰", "t": "dash punctuation wavy", "d": "wavy dash" },
            { "s": "©", "t": "copyright", "d": "copyright" },
            { "s": "®", "t": "registered", "d": "registered" },
            { "s": "™", "t": "mark tm trademark", "d": "trade mark" },
            { "s": "🔟", "t": "keycap 10", "d": "keycap 10" },
            { "s": "💯", "t": "100 full hundred score", "d": "hundred points" },
            { "s": "🔠", "t": "ABCD input latin letters uppercase", "d": "input latin uppercase" },
            { "s": "🔡", "t": "abcd input latin letters lowercase", "d": "input latin lowercase" },
            { "s": "🔢", "t": "1234 input numbers", "d": "input numbers" },
            { "s": "🔣", "t": "??&% input", "d": "input symbols" },
            { "s": "🔤", "t": "abc alphabet input latin letters", "d": "input latin letters" },
            { "s": "🅰", "t": "a blood type", "d": "A button (blood type)" },
            { "s": "🆎", "t": "ab blood type", "d": "AB button (blood type)" },
            { "s": "🅱", "t": "b blood type", "d": "B button (blood type)" },
            { "s": "🆑", "t": "cl", "d": "CL button" },
            { "s": "🆒", "t": "cool", "d": "COOL button" },
            { "s": "🆓", "t": "free", "d": "FREE button" },
            { "s": "ℹ", "t": "i information", "d": "information" },
            { "s": "🆔", "t": "id identity", "d": "ID button" },
            { "s": "Ⓜ", "t": "circle m", "d": "circled M" },
            { "s": "🆕", "t": "new", "d": "NEW button" },
            { "s": "🆖", "t": "ng", "d": "NG button" },
            { "s": "🅾", "t": "blood type o", "d": "O button (blood type)" },
            { "s": "🆗", "t": "OK", "d": "OK button" },
            { "s": "🅿", "t": "parking", "d": "P button" },
            { "s": "🆘", "t": "help sos", "d": "SOS button" },
            { "s": "🆙", "t": "mark up", "d": "UP! button" },
            { "s": "🆚", "t": "versus vs", "d": "VS button" },
            { "s": "🈁", "t": "“here” Japanese katakana ??", "d": "Japanese “here” button" },
            { "s": "🈂", "t": "“service charge” Japanese katakana ?", "d": "Japanese “service charge” button" },
            { "s": "🈷", "t": "“monthly amount” ideograph Japanese ?", "d": "Japanese “monthly amount” button" },
            { "s": "🈶", "t": "“not free of charge” ideograph Japanese ?", "d": "Japanese “not free of charge” button" },
            { "s": "🈯", "t": "“reserved” ideograph Japanese ?", "d": "Japanese “reserved” button" },
            { "s": "🉐", "t": "“bargain” ideograph Japanese ?", "d": "Japanese “bargain” button" },
            { "s": "🈹", "t": "“discount” ideograph Japanese ?", "d": "Japanese “discount” button" },
            { "s": "🈚", "t": "“free of charge” ideograph Japanese ?", "d": "Japanese “free of charge” button" },
            { "s": "🈲", "t": "“prohibited” ideograph Japanese ?", "d": "Japanese “prohibited” button" },
            { "s": "🉑", "t": "“acceptable” ideograph Japanese ?", "d": "Japanese “acceptable” button" },
            { "s": "🈸", "t": "“application” ideograph Japanese ?", "d": "Japanese “application” button" },
            { "s": "🈴", "t": "“passing grade” ideograph Japanese ?", "d": "Japanese “passing grade” button" },
            { "s": "🈳", "t": "“vacancy” ideograph Japanese ?", "d": "Japanese “vacancy” button" },
            { "s": "㊗", "t": "“congratulations” ideograph Japanese ?", "d": "Japanese “congratulations” button" },
            { "s": "㊙", "t": "“secret” ideograph Japanese ?", "d": "Japanese “secret” button" },
            { "s": "🈺", "t": "“open for business” ideograph Japanese ?", "d": "Japanese “open for business” button" },
            { "s": "🈵", "t": "“no vacancy” ideograph Japanese ?", "d": "Japanese “no vacancy” button" },
            { "s": "▪", "t": "geometric square", "d": "black small square" },
            { "s": "▫", "t": "geometric square", "d": "white small square" },
            { "s": "◻", "t": "geometric square", "d": "white medium square" },
            { "s": "◼", "t": "geometric square", "d": "black medium square" },
            { "s": "◽", "t": "geometric square", "d": "white medium-small square" },
            { "s": "◾", "t": "geometric square", "d": "black medium-small square" },
            { "s": "⬛", "t": "geometric square", "d": "black large square" },
            { "s": "⬜", "t": "geometric square", "d": "white large square" },
            { "s": "🔶", "t": "diamond geometric orange", "d": "large orange diamond" },
            { "s": "🔷", "t": "blue diamond geometric", "d": "large blue diamond" },
            { "s": "🔸", "t": "diamond geometric orange", "d": "small orange diamond" },
            { "s": "🔹", "t": "blue diamond geometric", "d": "small blue diamond" },
            { "s": "🔺", "t": "geometric red", "d": "red triangle pointed up" },
            { "s": "🔻", "t": "down geometric red", "d": "red triangle pointed down" },
            { "s": "💠", "t": "comic diamond geometric inside", "d": "diamond with a dot" },
            { "s": "🔘", "t": "button geometric radio", "d": "radio button" },
            { "s": "🔲", "t": "button geometric square", "d": "black square button" },
            { "s": "🔳", "t": "button geometric outlined square", "d": "white square button" },
            { "s": "⚪", "t": "circle geometric", "d": "white circle" },
            { "s": "⚫", "t": "circle geometric", "d": "black circle" },
            { "s": "🔴", "t": "circle geometric red", "d": "red circle" },
            { "s": "🔵", "t": "blue circle geometric", "d": "blue circle" },
            { "s": "🏁", "t": "checkered chequered racing", "d": "chequered flag" },
            { "s": "🚩", "t": "post", "d": "triangular flag" },
            { "s": "🎌", "t": "celebration cross crossed Japanese", "d": "crossed flags" },
            { "s": "🏴", "t": "waving", "d": "black flag" },
            { "s": "🏳", "t": "waving", "d": "white flag" },
            */
        ]
    },
    'faces': {
        'title': 'Faces (ಠ_ಠ)',
        'searchable' : false,
        'items': [
            { "s": "( ͡° ͜ʖ ͡°)", "t": "face lenny", "desc": "lenny face" },
            { "s": "ᕦ( ͡° ͜ʖ ͡°)ᕤ", "t": "face lenny", "desc": "lenny face" },
            { "s": "( ͡o ͜ʖ ͡o)", "t": "face lenny", "desc": "lenny face" },
            { "s": "(ง ͠° ͟ل͜ ͡°)ง", "t": "face lenny", "desc": "lenny face" },
            { "s": "( ‾ʖ̫‾)", "t": "face lenny", "desc": "lenny face" },
            { "s": "( ͡°╭͜ʖ╮͡° )", "t": "face lenny", "desc": "lenny face" },
            { "s": "ᕦ( ͡°╭͜ʖ╮͡° )ᕤ", "t": "face lenny", "desc": "lenny face" },

            { "s": "¯\_(ツ)_/¯", "t": "face shrug dunno", "desc": "shrugging" },

            { "s": 'ʢ◉ᴥ◉ʡ', "t": "face cat", "desc": "kitty face" },
            { "s": "^⨀ᴥ⨀^", "t": "face cat", "desc": "kitty face" },
            { "s": "◕_◕", "t": "face flower", "desc": "flower girl" },
            { "s": 'ᘳ◕ᴥ◕ᘰ', "t": "face lenny", "desc": "flower girl" },
            { "s": '(•_•)', "t": "face lenny", "desc": "lenny face" },
            { "s": '( •_•)', "t": "face lenny", "desc": "lenny face" },
            { "s": '@_@', "t": "face dizzy", "desc": "dizzy face" },

            { "s": '>⌐■-■', "t": "face deal sunglasses", "desc": "deal with it" },
            { "s": '(⌐■_■)', "t": "face deal sunglasses", "desc": "deal with it" },
            { "s" : "(•_•) ( •_•)>⌐■-■ (⌐■_■)", "t": "deal", "desc": "deal with it" },

            { "s" : "( ಠ ͜ʖರೃ)", "t": "monocle", "desc": "monocle" },

            { "s": "^_^", "t": "face joy", "desc": "happy face" },
            { "s": "(ಠ_ಠ)", "t": "face disapproval", "desc": "face of disapproval" },
            { "s": "{ಠ_ಠ}", "t": "face lenny", "desc": "lenny face" },
            { "s": "(⋟﹏⋞)", "t": "face angry", "desc": "angry ouch face" },
            { "s": "ʕʘ̅͜ʘ̅ʔ", "t": "face", "desc": "lenny face" },
            { "s": "ʕ•ᴥ•ʔ", "t": "face pedobear", "desc": "pedobear" },
            { "s": "ᶘ ᵒᴥᵒᶅ", "t": "face pedobear", "desc": "pedobear" },
        ]
    },
    'emoticons': {
        'title': 'Unicode ༼°□° ༽',
        'searchable' : false,
        'items': [
            
            { "s": "(╯°□°）╯︵ ┻━┻", "t": "flip table upset", "desc": "throwing table" },
            { "s": "┬──┬ ノ( ゜-゜ノ)", "t": "table", "desc": "putting table down" },
            { "s": "┌∩┐(◣_◢)┌∩┐", "t": "fingers fuck evil", "desc": "evil fuck" },
            { "s": "༼ つ ◕_◕ ༽つ", "t": "bubble monster please give", "desc": "cute bubble monster" },
            { "s": "(つ -‘ _ ‘- )つ", "t": "bubble monster please give", "desc": "cute bubble monster" },
            { "s": "(づ｡◕‿‿◕｡)づ ", "t": "bubble monster emotion please give", "desc": "cute bubble monster" },
            { "s": "ᕦ(ò_ó*)ᕤ", "t": "splatoon", "desc": "splatoon" },

            { "s": "༼ ºل͟º ༽", "t": "mob monster", "desc": "mob" },

            { "s": "(V)_(°;;;°)_(V)", "t": "zoidberg", "desc": "why not zoidberg" },
            { "s": "٩(͡๏̯͡๏)۶", "t": "frown", "desc": "frowny face" },
            { "s": "ლ(ಠ益ಠლ)", "t": "yuno", "desc": "why you no" },
            { "s": "(ノಠ益ಠ)ノ彡", "t": "rage", "desc": "rage" },
            { "s": "ヽ༼ຈل͜ຈ༽ﾉ", "t": "raise dongers", "desc": "raise your dongers" },

            { "s": "ˁ˚ᴥ˚ˀ", "t": "animal pet bear", "desc": "pet" },
            { "s": "'-'_@_", "t": "animal snail", "desc": "snail" },
            { "s": "<°)))><", "t": "animal fish", "desc": "fish left" },
            { "s": "><)))°>", "t": "animal fish", "desc": "fish right" },
            { "s": "Ƹ̵̡Ӝ̵̨̄Ʒ", "t": "animal butterfly", "desc": "butterfly" },
            { "s": "=^..^=", "t": "animal cat", "desc": "kitty" },
            { "s": "(°Д°)", "t": "animal duck", "desc": "duck" },
            { "s": "(⦿ᴥ⦿)ˀ", "t": "animal bird", "desc": "bird" },
            { "s": "~(‾▿‾)~", "t": "animal bird", "desc": "angry bird" },
            { "s": "( o ) ( o )", "t": "eyes boobs", "desc": "two eyes" },

            { "s": "(⋗_⋖)", "t": "lol xd haha", "desc": "xd" },
            { "s": "(✖╭╮✖)", "t": "dead dizzy sick", "desc": "dizzy" },
            { "s": "‘(◣_◢)’", "t": "angry", "desc": "angry guy" },
            { "s": "(◢_◣)", "t": "sad", "desc": "sad face" },
            { "s": "\,,/(◣_◢)\,,/", "t": "angry", "desc": "angry face" },
            { "s": "┌∩┐(◣_◢)┌∩┐", "t": "fuck you", "desc": "fuck you" },
                    
            { "s": "♪ ♫ ♩ ♬ ♭ ♮", "t": "music", "desc": "notes" },
            { "s": "][_ ([]) ][_", "t": "lol", "desc": "lol" },
            { "s": "ⓛⓞⓥⓔ", "t": "love", "desc": "love" },

            { "s": "இڿڰۣ-ڰۣ—", "t": "flower", "desc": "rose" },
            { "s": "@-`-,--", "t": "flower", "desc": "rose" },
            { "s": "--------{---(@", "t": "flower", "desc": "rose" },
            { "s": "웃❤유", "t": "love", "desc": "lenny face" },
            { "s": "(♥_♥)", "t": "love", "desc": "in love" },
            { "s": "★★★★★", "t": "star stars", "desc": "five stars" },

            { "s": "╭∩╮╭∩╮", "t": "fingers fuck", "desc": "fuck you" },
            { "s": "(Ο_Ο)╭∩╮", "t": "face fingers fuck", "desc": "fuck you" },
            { "s": "╭∩╮(Ο_Ο)╭∩╮", "t": "face fingers fuck", "desc": "fuck you" },
            { "s": "(ಠ_ಠ)┌∩┐", "t": "face fingers fuck", "desc": "fuck you" },
            { "s": "╭∩╮ (òÓ,) ╭∩╮", "t": "face fingers fuck", "desc": "fuck you" },

            { "s": "┣▇▇▇═─", "t": "syringe needle", "desc": "inject" },
            { "s": "())==[:::::::::::::>", "t": "sword", "desc": "sword" },
            { "s": "︻╦╤─", "t": "gun weapon rifle", "desc": "firearm" },
            { "s": "’ ̿’\̵͇̿̿\з=( ͡ °_̯͡° )=ε/̵͇̿̿/’̿’̿ ̿\"", "t": "gun weapon fire", "desc": "shooting fire" },

            { "s": "▂▃▅▇█▓▒░۩۞۩", "t": "ascii gradient", "desc": "gradient" },
            { "s": "۩۞۩░▒▓█▇▅▃▂", "t": "ascii gradient", "desc": "gradient" },
            { "s": "║▌║█║▌│║▌║▌", "t": "ascii gradient", "desc": "gradient" },

            { "s": "█▒▒▒▒▒▒▒▒", "t": "ascii gradient", "desc": "gradient" },
            { "s": "███▒▒▒▒▒▒", "t": "ascii gradient", "desc": "gradient" },
            { "s": "███████▒▒", "t": "ascii gradient", "desc": "gradient" },
            { "s": "██████████", "t": "ascii gradient", "desc": "gradient" },
            { "s": "°º¤ø,¸¸,ø¤º°`°º¤ø,¸,ø¤°º¤ø,¸¸,ø¤º°`°º¤ø,¸", "t": "ascii wave", "desc": "wave" },

            { "s": "┏(-_-)┛", "t": "dance", "desc": "dance" },
            { "s": "┗(-_- )┓", "t": "dance", "desc": "dance" },
            { "s": "┗(-_-)┛", "t": "dance", "desc": "dance" },
            { "s": "┏(-_-)┓", "t": "dance", "desc": "dance" },
        ]
    },
   
};

var init = function () {
    // nav html
    var i = 0;
    var html;
    var category;
    for (category in allItems) {
        html = '<li';
        if (i === 0) {
            html += ' class="on" ';
        }
        i++;
        html += ' data-category="' + category + '">' + allItems[category].title + '</li>';
        $("nav ul").append(html);
        $('section#content').append('<div class="category" id="' + category + '" style="display:none;"></div>');
    }
    // nav click
    $("nav ul li").click(function (el) {
        $('section#content div.category').hide();
        $('nav ul li').removeClass('on');
        $('section#search').hide();
        $(el).addClass('on');
        if(allItems[$(el.target).attr('data-category')].searchable) {
            $('section#search').show();
        }
        $('section#content div.category#' + $(el.target).attr('data-category')).show();
    });
    for (category in allItems) {
        $('section#content div.category#' + category).show();
        break;
    }
    // content html
    for (category in allItems) {
        html = '';
        for (var item in allItems[category].items) {
            html += '<button class="' + category + ' item" title="' + allItems[category].items[item].d + ' (' + allItems[category].items[item].t + ')' + '" data-clipboard-text="' + allItems[category].items[item].s + '" data-clipboard-tags="' + allItems[category].items[item].t + '" data-clipboard-description="' + allItems[category].items[item].d + '">' + allItems[category].items[item].s + '</button>';
        }
        $('section#content div.category#' + category).html(html);
    }
    // search handler
    $('#q').keyup(function() {
        var val = $('#q').val();
        if(val == '') {
            $('section#content div.category#emojis button').each(function(idx) {
                $(this).show();
            });
        }
        else {
            var keywords = [];
            if(val.indexOf(' ')>=0) {
                keywords = val.split(' ');
            }
            else {
                keywords.push(val);
            }
            $('section#content div.category#emojis button').each(function(idx) {
                $(this).hide();
                var nbFoundKeywords = 0;
                for(var i in keywords) {
                    searchIn = $(this).attr('data-clipboard-tags') + ' ' + $(this).attr('data-clipboard-description');
                    searchInArr = searchIn.split(' ');
                    for(var j in searchInArr) {
                        if(searchInArr[j].indexOf(keywords[i])>=0) {    
                            nbFoundKeywords ++;
                        }
                    }
                }
                if(nbFoundKeywords >= keywords.length) {
                    $(this).show();
                }
            });
        }
        
    });
    // gestion du clic
    $("section#content button").on("click", function() {
        $('#selection').val($('#selection').val() + $(this).attr('data-clipboard-text'));
        var copyFrom = document.createElement("textarea");
        copyFrom.textContent =  $('#selection').val();
        var body = document.getElementsByTagName('body')[0];
        body.appendChild(copyFrom);
        copyFrom.select();
        document.execCommand('copy');
        body.removeChild(copyFrom);
    });
};

init();